services:
  app:
    image: node
    container_name: app
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "if [[ ${NODE_ENV} == "production" ]]; then
      npm i pm2 -g && npm i  && npm run build && npm run migrate && npm run start:prod;
      else
      npm i && npm run start:dev;
      fi"
    ports:
      - 5555:5555
    environment:
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      DEV_DATABASE: ${DEV_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PROD_DATABASE: ${PROD_DATABASE}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      MAILGUN_SENDER_USER: ${MAILGUN_SENDER_USER}
      MAILGUN_USERNAME: ${MAILGUN_USERNAME}
      MAILGUN_API_URL: ${MAILGUN_API_URL}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_MESSAGING_SERVICE_SID: ${TWILIO_MESSAGING_SERVICE_SID}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      REDIS_URL: ${REDIS_URL}
      RABBITMQ_URI: ${RABBITMQ_URI}
      ELASTIC_NODE: ${ELASTIC_NODE}
      SSL_KEY_PATH: ${SSL_KEY_PATH}
      SSL_CERT_PATH: ${SSL_CERT_PATH}
      SSL_CA_PATH: ${SSL_CA_PATH}
      SECURE_HOST: ${SECURE_HOST}
      PORT: ${PORT}

  postgresql-database:
    image: postgres
    container_name: postgresql-database
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./init-postgres.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis-database:
    image: redislabs/redismod
    container_name: redis-database
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  elastic-search:
    container_name: elastic-search
    image: elasticsearch:8.6.0
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - "http.port=9200"
      - "http.cors.allow-origin=http://localhost:8002"
      - "http.cors.enabled=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 8000
    ports:
      - 8000:8000

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight
    restart: always
    ports:
      - 8001:8001

  elastic-ui:
    container_name: elastic_ui
    image: appbaseio/dejavu
    restart: always    
    ports:
      - 8002:1358

volumes:
  postgresql-data:
  redis-data:
  rabbitmq:
  elastic-data:
  kibana:
