export const QUEUES = {
  ACCOUNT_NOTIFICATIONS: 'ACCOUNT_NOTIFICATIONS',
  TFA_MAIL_NOTIFICATIONS: 'TFA_MAIL_NOTIFICATIONS',
  SMS_NOTIFICATIONS: 'SMS_NOTIFICATIONS',
  REGISTER_MAIL_NOTIFICATION: 'REGISTER_MAIL_NOTIFICATION',
  SUBSCRIBER_NOTIFICATIONS: 'SUBSCRIBER_NOTIFICATIONS',
  SUBSCRIBER_MAILS_NOTIFICATIONS: 'SUBSCRIBER_MAILS_NOTIFICATIONS',
};
